version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on ${REPOSITORY_URI}
      - echo Building the Docker image...
      - docker build -t nginx .
      - docker tag nginx:latest ${REPOSITORY_URI}:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push ${REPOSITORY_URI}:latest
cache:
  paths:
    - "/root/.m2/**/*"

artifacts:
  files: imagedefinitions.json
